package com.friend.sharedpref

object SpKey {
    const val loginStatus = "loginStatus"
    const val authToken = "authToken"
    const val tokenExpireAt = "tokenExpireAt"
    const val refreshToken = "refreshToken"

    const val userName = "userName"
    const val fullName = "fullName"
    const val gender = "gender"
    const val dateOfBirth = "dateOfBirth"
    const val email = "email"
    const val interestedIn = "interestedIn"
    const val country = "country"
    const val state = "state"
    const val city = "city"
    const val zipCode = "zipCode"
    const val profilePicture = "profilePicture"
    const val bodyType = "bodyType"
    const val drinking = "drinking"
    const val eyes = "eyes"
    const val hair = "hair"
    const val height = "hair"
    const val interests = "interests"
    const val lookingFor = "lookingFor"
    const val smoking = "smoking"
    const val aboutYou = "aboutYou"
    const val title = "title"
    const val weight = "weight"
    const val whatsUp = "whatsUp"
}